version: "3.8"
services:
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT=Development
            CONNECTIONSTRINGS__DATABASE=Server=db;Database=salesdb;User=sa;Password=Challenge@123
        ports:
            - "0.0.0.0:5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Challenge@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
