version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Challenge@123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - sql_data_volume:/var/opt/mssql
volumes:
    sql_data_volume:
